#import "~graphql/fragments/product.gql"

query productRecommendations(
  $productId: ID!
  $intent: ProductRecommendationIntent
  $country: CountryCode!
  $language: LanguageCode!
) @inContext(country: $country, language: $language) {
  productRecommendations(productId: $productId, intent: $intent) {
    ...product
  }
}
